/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author ThinkPad
 */
public class CargarAlumnos extends javax.swing.JPanel {

    /**
     * Creates new form CargarAlumnos
     */
    public CargarAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nroDeDoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fechaNac = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        facuPerteneciente = new javax.swing.JTextField();
        botonCrear = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        jLabel2.setText("Nro de Documento");

        jLabel3.setText("Telefono");

        email.addActionListener(this::emailActionPerformed);

        jLabel4.setText("Email");

        telf.addActionListener(this::telfActionPerformed);

        jLabel5.setText("Fecha de Nac");

        fechaNac.addActionListener(this::fechaNacActionPerformed);

        jLabel6.setText("Facultad a la que pertence");

        facuPerteneciente.addActionListener(this::facuPertenecienteActionPerformed);

        botonCrear.setText("Crear");
        botonCrear.addActionListener(this::botonCrearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(email)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(nroDeDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(facuPerteneciente, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(telf, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))))
                    .addComponent(botonCrear))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nroDeDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facuPerteneciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(botonCrear)
                .addContainerGap(238, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void telfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telfActionPerformed

    private void fechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaNacActionPerformed

    private void facuPertenecienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facuPertenecienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facuPertenecienteActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
       
        switch (modo) {

            case "CREAR" -> {
                boolean creado = Controller.ControladorView.agregarAlumno(
                        nombre.getText(), nroDeDoc.getText(), email.getText(),
                        telf.getText(), fechaNac.getText(), facuPerteneciente.getText());

                if (creado) {
                    nombre.setText("");
                    nroDeDoc.setText("");
                    email.setText("");
                    telf.setText("");
                    fechaNac.setText("");
                    facuPerteneciente.setText("");
                }
            }

            case "EDITAR" -> {
                boolean actualizado = Controller.ControladorView.editarAlumno(
                        this.docOriginal, nroDeDoc.getText(), nombre.getText(), email.getText(),
                        telf.getText(), fechaNac.getText(), facuPerteneciente.getText());

                if (actualizado && panelOrigen != null) {
                    VentanaPrincipal principal = (VentanaPrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);
                    if (principal != null) {
                        EditarAlumno nuevoPanelEditar = new EditarAlumno(principal);
                        principal.mostrarEnCentro(nuevoPanelEditar);
                    }
                }
            }
        }
    }//GEN-LAST:event_botonCrearActionPerformed
    public void configurar(String modo, Clases.Model.Alumno alumno, EditarAlumno origen) {
        this.modo = modo;
        this.panelOrigen = origen; 
        switch (modo) {
            case "CREAR" -> {
                botonCrear.setText("Crear");
                nroDeDoc.setEditable(true);
            }
            case "EDITAR" -> {
                precargarDatos(alumno);
            }
        }
    }
    public void precargarDatos(Clases.Model.Alumno alumno) {
            this.modo = "EDITAR";
            this.docOriginal = alumno.getNroDeDocumento();

            nombre.setText(alumno.getNombreCompleto());
            nroDeDoc.setText(alumno.getNroDeDocumento());
            email.setText(alumno.getEmail());
            telf.setText(alumno.getTelefono());
            fechaNac.setText(alumno.getFechaDeNacimiento());
            facuPerteneciente.setText(alumno.getFacultadPerteneciente());
            botonCrear.setText("Guardar cambios");

            nroDeDoc.setEditable(true);
        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrear;
    private javax.swing.JTextField email;
    private javax.swing.JTextField facuPerteneciente;
    private javax.swing.JTextField fechaNac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nroDeDoc;
    private javax.swing.JTextField telf;
    // End of variables declaration//GEN-END:variables
    private String modo = "CREAR";
    private EditarAlumno panelOrigen;
    private String docOriginal = "";

}
