/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author ThinkPad
 */
public class CargarPrestamos extends javax.swing.JPanel {

    /**
     * Creates new form CargarAlumnos
     */
    public CargarPrestamos() {
        initComponents();
        cargarTablaAlumnos();
    }
    

    private void cargarTablaAlumnos() {
        javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tablaAlumno2.getTabla().getModel();
        modelo.setRowCount(0);
        for (Clases.Model.Alumno a : Controller.ControladorView.obtenerAlumnos()) {
            modelo.addRow(new Object[]{
                a.getNombreCompleto(),
                a.getNroDeDocumento(),
                a.getEmail(),
                a.getTelefono(),
                a.getFechaDeNacimiento(),
                a.getFacultadPerteneciente()
            });
        }
    }
    public void CargarPrestamos() {
        initComponents();
        botonSgte.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String docAlumno = nroDeDoc.getText().trim();
                Clases.Model.Alumno alumno = Controller.ControladorView.buscarAlumno(docAlumno);
                if (alumno == null) {
                    return; 
                }
                VentanaPrincipal principal = (VentanaPrincipal) javax.swing.SwingUtilities.getWindowAncestor(CargarPrestamos.this);
                if (principal != null) {
                    CargarPrestamos2 paso2 = new CargarPrestamos2();
                    paso2.setAlumno(alumno.getNombreCompleto());
                    principal.mostrarEnCentro(paso2);
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        tablaAlumno2 = new View.TablaAlumno();
        nroDeDoc = new javax.swing.JTextField();
        botonSgte = new javax.swing.JButton();

        jLabel5.setText("Dame el Nro de Documento del Alumno que prestara");

        botonSgte.setText("Siguiente");
        botonSgte.addActionListener(this::botonSgteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaAlumno2, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nroDeDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(botonSgte))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tablaAlumno2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nroDeDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSgte)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonSgteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSgteActionPerformed

        String docAlumno = nroDeDoc.getText().trim();
        Clases.Model.Alumno alumno = Controller.ControladorView.buscarAlumno(docAlumno);
        if (alumno == null) {
            return;
        }

        VentanaPrincipal principal
                = (VentanaPrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (principal != null) {
            CargarPrestamos2 paso2 = new CargarPrestamos2();
            paso2.setAlumno(alumno.getNombreCompleto());
            principal.mostrarEnCentro(paso2);
        }
    }//GEN-LAST:event_botonSgteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSgte;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nroDeDoc;
    private View.TablaAlumno tablaAlumno2;
    // End of variables declaration//GEN-END:variables
    private String alumnoSeleccionado = "";

    public void setAlumno(String nombreAlumno) {
        this.alumnoSeleccionado = nombreAlumno;
    }

}
