/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author ThinkPad
 */
public class CargarLibros extends javax.swing.JPanel {

    /**
     * Creates new form CargarAlumnos
     */
    public CargarLibros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        editorial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        anhoPublicacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        autor = new javax.swing.JTextField();
        botonCrear = new javax.swing.JButton();

        jLabel1.setText("Titulo");

        jLabel2.setText("Editorial");

        jLabel3.setText("Autor");

        anhoPublicacion.addActionListener(this::anhoPublicacionActionPerformed);

        jLabel4.setText("Año de Publicacion");

        autor.addActionListener(this::autorActionPerformed);

        botonCrear.setText("Crear");
        botonCrear.addActionListener(this::botonCrearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(anhoPublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonCrear))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anhoPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(botonCrear)
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void anhoPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anhoPublicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anhoPublicacionActionPerformed

    private void autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        switch (modo) {
            case "CREAR" -> {
                Controller.ControladorView.agregarLibro(
                    titulo.getText(), editorial.getText(),
                    autor.getText(), anhoPublicacion.getText());
                titulo.setText("");
                editorial.setText("");
                autor.setText("");
                anhoPublicacion.setText("");
            }
            case "EDITAR" -> {
                boolean ok = Controller.ControladorView.editarLibro(
                    libroId, titulo.getText(), editorial.getText(),
                    autor.getText(), anhoPublicacion.getText());

                if (ok && panelOrigen != null) {
                    VentanaPrincipal principal = (VentanaPrincipal)
                        javax.swing.SwingUtilities.getWindowAncestor(this);
                    if (principal != null) {
                        panelOrigen.cargarTabla(); // actualiza la tabla
                        principal.mostrarEnCentro(panelOrigen); // vuelve a EditarLibro
                    }
                }
            }
        }

    }//GEN-LAST:event_botonCrearActionPerformed
    
    public void precargarDatos(Clases.Model.Libro libro, EditarLibro origen) {
        this.modo = "EDITAR";
        this.libroId = libro.getId();
        this.panelOrigen = origen;
        titulo.setText(libro.getTitulo());
        editorial.setText(libro.getEditorial());
        autor.setText(libro.getAutor());
        anhoPublicacion.setText(libro.getAnhoDePublicacion());
        botonCrear.setText("Guardar cambios");
    }
    
    private String modo = "CREAR";
    private int libroId = -1;
    private EditarLibro panelOrigen;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anhoPublicacion;
    private javax.swing.JTextField autor;
    private javax.swing.JButton botonCrear;
    private javax.swing.JTextField editorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
