/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author ThinkPad
 */
public class CargarPrestamos2 extends javax.swing.JPanel {

    /**
     * Creates new form CargarAlumnos
     */
    public CargarPrestamos2() {
        initComponents();
        botonSgte.addActionListener(e -> {
            String idsTexto = nroDeDoc.getText().trim();       
            String fechaPrestamo = fechaPrestamo1.getText().trim();  
            String fechaDevol = fechaDeEntrega.getText().trim();  

            if (idsTexto.isEmpty() || fechaPrestamo.isEmpty() || fechaDevol.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(null,
                        "Completá todos los campos.", "Campos vacíos",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

          
            java.util.List<String> titulosLibros = new java.util.ArrayList<>();
            for (String idStr : idsTexto.split(",")) {
                try {
                    int id = Integer.parseInt(idStr.trim());
                    Clases.Model.Libro libro
                            = Repositorios.RepositorioLibros.libros.get(id);
                    if (libro == null) {
                        javax.swing.JOptionPane.showMessageDialog(null,
                                "No existe un libro con ID: " + id, "ID inválido",
                                javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    titulosLibros.add(libro.getTitulo());
                } catch (NumberFormatException ex) {
                    javax.swing.JOptionPane.showMessageDialog(null,
                            "ID inválido: '" + idStr.trim() + "'. Usá solo números separados por coma.",
                            "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

       
            Controller.ControladorView.agregarPrestamo(
                    alumnoSeleccionado,
                    String.join(",", titulosLibros),
                    fechaPrestamo,
                    fechaDevol
            );

       
            nroDeDoc.setText("");
            fechaPrestamo1.setText("");
            fechaDeEntrega.setText("");
        });
    }
    private String alumnoSeleccionado = "";

    public void setAlumno(String nombreAlumno) {
        this.alumnoSeleccionado = nombreAlumno;
    }

    @Override
    public void addNotify() {
        super.addNotify();
        cargarTablaLibros();
    }
    private void cargarTablaLibros() {
        javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tablaLibro1.getTabla().getModel();
        modelo.setRowCount(0);
        for (Clases.Model.Libro l : Controller.ControladorView.obtenerLibrosDisponibles()) { 
            modelo.addRow(new Object[]{
                l.getId(),
                l.getTitulo(),
                l.getEditorial(),
                l.getAnhoDePublicacion(),
                l.getAutor()
            });
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        nroDeDoc = new javax.swing.JTextField();
        botonSgte = new javax.swing.JButton();
        tablaLibro1 = new View.TablaLibro();
        jLabel6 = new javax.swing.JLabel();
        fechaDeEntrega = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fechaPrestamo1 = new javax.swing.JTextField();

        jLabel5.setText("Dime el  ID  o los IDs del libro o los libros a prestar, separados por coma");

        botonSgte.setText("Siguiente");
        botonSgte.addActionListener(this::botonSgteActionPerformed);

        jLabel6.setText("Dame la fecha del Prestamo en YYYY-MM-DD");

        jLabel7.setText("Fecha a entregar  YYYY-MM-DD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaLibro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSgte)
                    .addComponent(nroDeDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(fechaDeEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(fechaPrestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(755, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tablaLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(nroDeDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addComponent(fechaPrestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechaDeEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(botonSgte)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonSgteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSgteActionPerformed
        // TODO add your handling code here:
        cargarTablaLibros();
    }//GEN-LAST:event_botonSgteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSgte;
    private javax.swing.JTextField fechaDeEntrega;
    private javax.swing.JTextField fechaPrestamo1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nroDeDoc;
    private View.TablaLibro tablaLibro1;
    // End of variables declaration//GEN-END:variables
}
