/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author HP
 */
public class EditarAlumno extends javax.swing.JPanel {

    /**
     * Creates new form EditarAlumno
     */
    public EditarAlumno() {
        initComponents();
        cargarTabla();
        panelEdicion = crearPanelEdicion();
        panelEdicion.setVisible(false);
        add(panelEdicion, java.awt.BorderLayout.CENTER);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        campoBusqueda = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Ingrese el nr de Documento");

        campoBusqueda.addActionListener(this::campoBusquedaActionPerformed);

        botonBuscar.setText("Editar");
        botonBuscar.addActionListener(this::botonBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(botonBuscar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar))
                .addGap(0, 45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Carga todos los alumnos en la tabla al abrir el panel
private void cargarTabla() {
    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();
    modelo.setRowCount(0);
    for (Clases.Model.Alumno a : Controller.ControladorView.obtenerAlumnos()) {
        modelo.addRow(new Object[]{
            a.getNombreCompleto(),
            a.getNroDeDocumento(),
            a.getEmail(),
            a.getTelefono(),
            a.getFechaDeNacimiento(),
            a.getFacultadPerteneciente()
        });
    }
}

// Crea el formulario de edición (los campos)
private javax.swing.JPanel crearPanelEdicion() {
    javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(7, 2, 10, 10));
    panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

    campoNombre    = new javax.swing.JTextField();
    campoDoc       = new javax.swing.JTextField();
    campoEmail     = new javax.swing.JTextField();
    campoTelf      = new javax.swing.JTextField();
    campoFechaNac  = new javax.swing.JTextField();
    campoFacultad  = new javax.swing.JTextField();
    botonGuardar   = new javax.swing.JButton("Guardar cambios");

    panel.add(new javax.swing.JLabel("Nombre:"));        panel.add(campoNombre);
    panel.add(new javax.swing.JLabel("Documento:"));     panel.add(campoDoc);
    panel.add(new javax.swing.JLabel("Email:"));         panel.add(campoEmail);
    panel.add(new javax.swing.JLabel("Teléfono:"));      panel.add(campoTelf);
    panel.add(new javax.swing.JLabel("Fecha Nac:"));     panel.add(campoFechaNac);
    panel.add(new javax.swing.JLabel("Facultad:"));      panel.add(campoFacultad);
    panel.add(new javax.swing.JLabel(""));               panel.add(botonGuardar);

    botonGuardar.addActionListener(e -> guardarCambios());
    return panel;
}
    
    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed

        String doc = campoBusqueda.getText().trim();
            if (doc.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresá el número de documento.");
            return;
        }

        Clases.Model.Alumno alumno = Controller.ControladorView.buscarAlumno(doc);
        if (alumno == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún alumno con ese documento.");
            return;
        }

    // Llenar los campos con los datos encontrados
        campoNombre.setText(alumno.getNombreCompleto());
        campoDoc.setText(alumno.getNroDeDocumento());
        campoEmail.setText(alumno.getEmail());
        campoTelf.setText(alumno.getTelefono());
        campoFechaNac.setText(alumno.getFechaDeNacimiento());
        campoFacultad.setText(alumno.getFacultadPerteneciente());

    // Ocultar la tabla y mostrar el formulario
        jScrollPane1.setVisible(false);
        panelEdicion.setVisible(true);
        revalidate();
        repaint();
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void campoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBusquedaActionPerformed
    
    private void guardarCambios() {
        Controller.ControladorView.editarAlumno(
            campoBusqueda.getText().trim(),
            campoNombre.getText(),
            campoEmail.getText(),
            campoTelf.getText(),
            campoFechaNac.getText(),
            campoFacultad.getText()
        );

    // Volver a mostrar la tabla actualizada
        jScrollPane1.setVisible(true);
        panelEdicion.setVisible(false);
        cargarTabla();
        revalidate();
        repaint();
    }
    
    private javax.swing.JPanel panelEdicion;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoDoc;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoTelf;
    private javax.swing.JTextField campoFechaNac;
    private javax.swing.JTextField campoFacultad;
    private javax.swing.JButton botonGuardar;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
