/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


package View;

/**
 *
 * @author HP
 */
public class EditarAlumno extends javax.swing.JPanel {

    /**
     * Creates new form EditarAlumno
     * @param ventanaPrincipal
     */
    public EditarAlumno(VentanaPrincipal ventanaPrincipal) {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoBusqueda = new javax.swing.JTextField();
        botonEditar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAlumno1 = new View.TablaAlumno();

        jLabel1.setText("Ingrese el nr de Documento");

        campoBusqueda.addActionListener(this::campoBusquedaActionPerformed);

        botonEditar.setText("Editar");
        botonEditar.addActionListener(this::botonEditarActionPerformed);

        jScrollPane2.setViewportView(tablaAlumno1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(botonEditar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(594, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEditar))
                .addGap(0, 45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    void cargarTabla() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaAlumno1.getTabla().getModel();
        modelo.setRowCount(0);
        for (Clases.Model.Alumno a : Controller.ControladorView.obtenerAlumnos()) {
            modelo.addRow(new Object[]{
                a.getNombreCompleto(),
                a.getNroDeDocumento(),
                a.getEmail(),
                a.getTelefono(),
                a.getFechaDeNacimiento(),
                a.getFacultadPerteneciente()
        });
    }
}


    private javax.swing.JPanel crearPanelEdicion() {
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(7, 2, 10, 10));
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        campoNombre    = new javax.swing.JTextField();
        campoDoc       = new javax.swing.JTextField();
        campoEmail     = new javax.swing.JTextField();
        campoTelf      = new javax.swing.JTextField();
        campoFechaNac  = new javax.swing.JTextField();
        campoFacultad  = new javax.swing.JTextField();
        botonGuardar   = new javax.swing.JButton("Guardar cambios");

        panel.add(new javax.swing.JLabel("Nombre:"));        panel.add(campoNombre);
        panel.add(new javax.swing.JLabel("Documento:"));     panel.add(campoDoc);
        panel.add(new javax.swing.JLabel("Email:"));         panel.add(campoEmail);
        panel.add(new javax.swing.JLabel("Teléfono:"));      panel.add(campoTelf);
        panel.add(new javax.swing.JLabel("Fecha Nac:"));     panel.add(campoFechaNac);
        panel.add(new javax.swing.JLabel("Facultad:"));      panel.add(campoFacultad);
        panel.add(new javax.swing.JLabel(""));               panel.add(botonGuardar);

        botonGuardar.addActionListener(e -> guardarCambios());
        return panel;
}
    
    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed

        String doc = campoBusqueda.getText().trim();
        if (doc.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresá el número de documento.");
            return;
        }
        Clases.Model.Alumno alumno = Controller.ControladorView.buscarAlumno(doc);
        if (alumno == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Alumno no encontrado.");
            return;
        }
        CargarAlumnos formulario = new CargarAlumnos();
        formulario.precargarDatos(alumno);
        ventanaPrincipal.mostrarEnCentro(formulario);

    }//GEN-LAST:event_botonEditarActionPerformed

    private void campoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBusquedaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoBusquedaActionPerformed
    
    private void guardarCambios() {
        Controller.ControladorView.editarAlumno(
            campoBusqueda.getText().trim(),
            campoDoc.getText().trim(),
            campoNombre.getText(),
            campoEmail.getText(),
            campoTelf.getText(),
            campoFechaNac.getText(),
            campoFacultad.getText()
        );

        jScrollPane2.setVisible(true);
        panelEdicion.setVisible(false);
        cargarTabla();
        revalidate();
        repaint();
    }
    
    private javax.swing.JPanel panelEdicion;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoDoc;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoTelf;
    private javax.swing.JTextField campoFechaNac;
    private javax.swing.JTextField campoFacultad;
    private javax.swing.JButton botonGuardar;
    private VentanaPrincipal ventanaPrincipal;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEditar;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private View.TablaAlumno tablaAlumno1;
    // End of variables declaration//GEN-END:variables


}
