/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ThinkPad
 */
public class SubMenus extends javax.swing.JFrame {
    private VentanaPrincipal ventanaPrincipal;
    private String menuActual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SubMenus.class.getName());

    /**
     * Creates new form SubMenus
     */
    public SubMenus(VentanaPrincipal ventanaPrincipal, String menuActual) {
    initComponents();
    this.ventanaPrincipal = ventanaPrincipal;
    this.menuActual = menuActual;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menus = new javax.swing.JPanel();
        botonListar = new View.BotonAmarilloAlPasar();
        botonAtras = new View.BotonAmarilloAlPasar();
        botonCrear = new View.BotonAmarilloAlPasar();
        botonEditar = new View.BotonAmarilloAlPasar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menus.setOpaque(false);

        botonListar.setBackground(new java.awt.Color(204, 102, 0));
        botonListar.setText("Listar");
        botonListar.setToolTipText("");
        botonListar.setContentAreaFilled(false);

        botonAtras.setBackground(new java.awt.Color(204, 102, 0));
        botonAtras.setText("Atras");
        botonAtras.setToolTipText("");
        botonAtras.setContentAreaFilled(false);
        botonAtras.addActionListener(this::botonAtrasActionPerformed);

        botonCrear.setBackground(new java.awt.Color(204, 102, 0));
        botonCrear.setText("Crear");
        botonCrear.setContentAreaFilled(false);
        botonCrear.addActionListener(this::botonCrearActionPerformed);

        botonEditar.setBackground(new java.awt.Color(204, 102, 0));
        botonEditar.setText("Editar");
        botonEditar.setToolTipText("");
        botonEditar.setContentAreaFilled(false);
        botonEditar.addActionListener(this::botonEditarActionPerformed);

        javax.swing.GroupLayout MenusLayout = new javax.swing.GroupLayout(Menus);
        Menus.setLayout(MenusLayout);
        MenusLayout.setHorizontalGroup(
            MenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenusLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(MenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        MenusLayout.setVerticalGroup(
            MenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenusLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(botonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        javax.swing.JPanel contenedorPadre = (javax.swing.JPanel) this.Menus.getParent();
        
        if (contenedorPadre != null) {
            java.awt.CardLayout layout = (java.awt.CardLayout) contenedorPadre.getLayout();
            layout.show(contenedorPadre, "card2"); 
        }
        ventanaPrincipal.limpiarCentro();
        
        
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // TODO add your handling code here:
        botonEditar.setVisible(false);
        botonListar.setVisible(false);
        switch (menuActual) {
            
            case "Alumnos"   -> {ventanaPrincipal.mostrarEnCentro(new CargarAlumnos());
            }
            case "Libros"    -> {ventanaPrincipal.mostrarEnCentro(new CargarLibros());
            } 
            case "Prestamos" -> {
            }
    }
        
    }//GEN-LAST:event_botonCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menus;
    private View.BotonAmarilloAlPasar botonAtras;
    private View.BotonAmarilloAlPasar botonCrear;
    private View.BotonAmarilloAlPasar botonEditar;
    private View.BotonAmarilloAlPasar botonListar;
    // End of variables declaration//GEN-END:variables
}
