/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
/**
 *
 * @author ThinkPad
 */
public class SubMenus extends javax.swing.JFrame {
    public VentanaPrincipal ventanaPrincipal;
    private String menuActual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SubMenus.class.getName());

    /**
     * Creates new form SubMenus
     */
    public SubMenus(VentanaPrincipal ventanaPrincipal, String menuActual) {
    initComponents();
    this.ventanaPrincipal = ventanaPrincipal;
    this.menuActual = menuActual;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menus = new javax.swing.JPanel();
        botonListar = new View.BotonAmarilloAlPasar();
        botonAtras = new View.BotonAmarilloAlPasar();
        botonCrear = new View.BotonAmarilloAlPasar();
        botonEditar = new View.BotonAmarilloAlPasar();
        botonBorrar = new View.BotonAmarilloAlPasar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menus.setOpaque(false);

        botonListar.setBackground(new java.awt.Color(204, 102, 0));
        botonListar.setText("Listar");
        botonListar.setToolTipText("");
        botonListar.setContentAreaFilled(false);
        botonListar.addActionListener(this::accionListar);

        botonAtras.setBackground(new java.awt.Color(204, 102, 0));
        botonAtras.setText("Atras");
        botonAtras.setToolTipText("");
        botonAtras.setContentAreaFilled(false);
        botonAtras.addActionListener(this::botonAtrasActionPerformed);

        botonCrear.setBackground(new java.awt.Color(204, 102, 0));
        botonCrear.setText("Crear");
        botonCrear.setContentAreaFilled(false);
        botonCrear.addActionListener(this::botonCrearActionPerformed);

        botonEditar.setBackground(new java.awt.Color(204, 102, 0));
        botonEditar.setText("Editar");
        botonEditar.setToolTipText("");
        botonEditar.setContentAreaFilled(false);
        botonEditar.addActionListener(this::botonEditarActionPerformed);

        botonBorrar.setBackground(new java.awt.Color(204, 102, 0));
        botonBorrar.setText("Borrar");
        botonBorrar.setToolTipText("");
        botonBorrar.setContentAreaFilled(false);
        botonBorrar.addActionListener(this::botonBorraraccionListar);

        javax.swing.GroupLayout MenusLayout = new javax.swing.GroupLayout(Menus);
        Menus.setLayout(MenusLayout);
        MenusLayout.setHorizontalGroup(
            MenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenusLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(MenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MenusLayout.setVerticalGroup(
            MenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenusLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(botonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        javax.swing.JPanel contenedorPadre = (javax.swing.JPanel) this.Menus.getParent();
        
        if (contenedorPadre != null) {
            java.awt.CardLayout layout = (java.awt.CardLayout) contenedorPadre.getLayout();
            layout.show(contenedorPadre, "card2"); 
        }
        ventanaPrincipal.limpiarCentro();
        
        
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        botonEditar.setVisible(false);
        botonCrear.setVisible(false);
        botonListar.setVisible(false);

        switch (menuActual) {

            case "Alumnos" -> {
                
                EditarAlumno form = new EditarAlumno(ventanaPrincipal);
                ventanaPrincipal.mostrarEnCentro(form);
            }

            case "Libros" -> {
                EditarLibro form = new EditarLibro(ventanaPrincipal);
                ventanaPrincipal.mostrarEnCentro(form);
            }
            case "Prestamos" -> {
                DevolverPrestamo form = new DevolverPrestamo(ventanaPrincipal);
                ventanaPrincipal.mostrarEnCentro(form);
            }
        }
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // TODO add your handling code here:
        botonEditar.setVisible(false);
        botonListar.setVisible(false);
        botonCrear.setVisible(false);
        switch (menuActual) {
            
            case "Alumnos"   -> {ventanaPrincipal.mostrarEnCentro(new CargarAlumnos());
            }
            case "Libros"    -> {ventanaPrincipal.mostrarEnCentro(new CargarLibros());
            } 
            case "Prestamos" -> {ventanaPrincipal.mostrarEnCentro(new CargarPrestamos());
            }
        }
        
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonBorraraccionListar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorraraccionListar
        // TODO add your handling code here:
        botonEditar.setVisible(false);
        botonCrear.setVisible(false);
        botonListar.setVisible(false);
        botonBorrar.setVisible(false);

        switch (menuActual) {

            case "Alumnos" -> {
                TablaAlumno tablaAlumno = new TablaAlumno();
                javax.swing.table.DefaultTableModel modelo =
                    (javax.swing.table.DefaultTableModel) tablaAlumno.getTabla().getModel();
                modelo.setRowCount(0);
                for (Clases.Model.Alumno a : Controller.ControladorView.obtenerAlumnos()) {
                    modelo.addRow(new Object[]{
                        a.getNombreCompleto(), a.getNroDeDocumento(),
                        a.getEmail(), a.getTelefono(),
                        a.getFechaDeNacimiento(), a.getFacultadPerteneciente()
                    });
                }
                tablaAlumno.getTabla().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

                javax.swing.JLabel labelId = new javax.swing.JLabel("Nro. Documento a borrar:");
                javax.swing.JTextField campoId = new javax.swing.JTextField(15);
                javax.swing.JButton btnConfirmar = new javax.swing.JButton("Confirmar borrado");
                btnConfirmar.setBackground(new java.awt.Color(180, 40, 40));
                btnConfirmar.setForeground(java.awt.Color.WHITE);

                tablaAlumno.getTabla().getSelectionModel().addListSelectionListener(e -> {
                    if (!e.getValueIsAdjusting() && tablaAlumno.getTabla().getSelectedRow() >= 0) {
                        int fila = tablaAlumno.getTabla().convertRowIndexToModel(tablaAlumno.getTabla().getSelectedRow());
                        campoId.setText(modelo.getValueAt(fila, 1).toString());
                    }
                });

                btnConfirmar.addActionListener(e -> {
                    String doc = campoId.getText().trim();
                    if (doc.isEmpty()) {
                        javax.swing.JOptionPane.showMessageDialog(null, "Ingresá el número de documento.", "Campo vacío", javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    Clases.Model.Alumno alumno = Controller.ControladorView.buscarAlumno(doc);
                    if (alumno == null) return;
                    int confirm = javax.swing.JOptionPane.showConfirmDialog(null,
                        "¿Borrar al alumno: " + alumno.getNombreCompleto() + "?",
                        "Confirmar borrado", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);
                    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                        Repositorios.RepositorioAlumno.alumnos.remove(doc);
                        javax.swing.JOptionPane.showMessageDialog(null, "Alumno borrado correctamente.");
                        modelo.setRowCount(0);
                        for (Clases.Model.Alumno a : Controller.ControladorView.obtenerAlumnos()) {
                            modelo.addRow(new Object[]{
                                a.getNombreCompleto(), a.getNroDeDocumento(),
                                a.getEmail(), a.getTelefono(),
                                a.getFechaDeNacimiento(), a.getFacultadPerteneciente()
                            });
                        }
                        campoId.setText("");
                    }
                });

                javax.swing.JPanel panelInferior = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 8));
                panelInferior.add(labelId);
                panelInferior.add(campoId);
                panelInferior.add(btnConfirmar);

                javax.swing.JPanel panelBorrar = new javax.swing.JPanel(new java.awt.BorderLayout());
                panelBorrar.add(tablaAlumno, java.awt.BorderLayout.CENTER);
                panelBorrar.add(panelInferior, java.awt.BorderLayout.SOUTH);

                ventanaPrincipal.mostrarEnCentro(panelBorrar);
            }

            case "Libros" -> {
                TablaLibro tablaLibro = new TablaLibro();
                javax.swing.table.DefaultTableModel modelo =
                    (javax.swing.table.DefaultTableModel) tablaLibro.getTabla().getModel();
                modelo.setRowCount(0);
                for (Clases.Model.Libro l : Controller.ControladorView.obtenerLibros()) {
                    modelo.addRow(new Object[]{
                        l.getId(), l.getTitulo(), l.getEditorial(),
                        l.getAnhoDePublicacion(), l.getAutor()
                    });
                }
                tablaLibro.getTabla().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

                javax.swing.JLabel labelId = new javax.swing.JLabel("ID del libro a borrar:");
                javax.swing.JTextField campoId = new javax.swing.JTextField(8);
                javax.swing.JButton btnConfirmar = new javax.swing.JButton("Confirmar borrado");
                btnConfirmar.setBackground(new java.awt.Color(180, 40, 40));
                btnConfirmar.setForeground(java.awt.Color.WHITE);

                tablaLibro.getTabla().getSelectionModel().addListSelectionListener(e -> {
                    if (!e.getValueIsAdjusting() && tablaLibro.getTabla().getSelectedRow() >= 0) {
                        int fila = tablaLibro.getTabla().convertRowIndexToModel(tablaLibro.getTabla().getSelectedRow());
                        campoId.setText(modelo.getValueAt(fila, 0).toString());
                    }
                });

                btnConfirmar.addActionListener(e -> {
                    String idStr = campoId.getText().trim();
                    if (idStr.isEmpty()) {
                        javax.swing.JOptionPane.showMessageDialog(null, "Ingresá el ID del libro.", "Campo vacío", javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    Clases.Model.Libro libro = Controller.ControladorView.buscarLibro(idStr);
                    if (libro == null) return;
                    int confirm = javax.swing.JOptionPane.showConfirmDialog(null,
                        "¿Borrar el libro: " + libro.getTitulo() + "?",
                        "Confirmar borrado", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);
                    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                        Repositorios.RepositorioLibros.libros.remove(libro.getId());
                        javax.swing.JOptionPane.showMessageDialog(null, "Libro borrado correctamente.");
                        modelo.setRowCount(0);
                        for (Clases.Model.Libro l : Controller.ControladorView.obtenerLibros()) {
                            modelo.addRow(new Object[]{
                                l.getId(), l.getTitulo(), l.getEditorial(),
                                l.getAnhoDePublicacion(), l.getAutor()
                            });
                        }
                        campoId.setText("");
                    }
                });

                javax.swing.JPanel panelInferior = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 8));
                panelInferior.add(labelId);
                panelInferior.add(campoId);
                panelInferior.add(btnConfirmar);

                javax.swing.JPanel panelBorrar = new javax.swing.JPanel(new java.awt.BorderLayout());
                panelBorrar.add(tablaLibro, java.awt.BorderLayout.CENTER);
                panelBorrar.add(panelInferior, java.awt.BorderLayout.SOUTH);

                ventanaPrincipal.mostrarEnCentro(panelBorrar);
            }

            case "Prestamos" -> {
                TablaPrestamo tablaPrestamo = new TablaPrestamo();
                javax.swing.table.DefaultTableModel modelo =
                    (javax.swing.table.DefaultTableModel) tablaPrestamo.getTabla().getModel();
                modelo.setRowCount(0);
                for (Clases.Model.Prestamo p : Controller.ControladorView.obtenerPrestamos()) {
                    String librosUnidos = String.join(", ", p.getLibros());
                    modelo.addRow(new Object[]{
                        p.getAlumno(), librosUnidos, p.getId(),
                        p.getFechaDePrestamo(), p.getFechaDevolucion(),
                        p.getFechaDevuelta() != null ? p.getFechaDevuelta() : "Pendiente",
                        p.verificarVencimiento()
                    });
                }
                tablaPrestamo.getTabla().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

                javax.swing.JLabel labelId = new javax.swing.JLabel("ID del préstamo a borrar:");
                javax.swing.JTextField campoId = new javax.swing.JTextField(8);
                javax.swing.JButton btnConfirmar = new javax.swing.JButton("Confirmar borrado");
                btnConfirmar.setBackground(new java.awt.Color(180, 40, 40));
                btnConfirmar.setForeground(java.awt.Color.WHITE);

                tablaPrestamo.getTabla().getSelectionModel().addListSelectionListener(e -> {
                    if (!e.getValueIsAdjusting() && tablaPrestamo.getTabla().getSelectedRow() >= 0) {
                        int fila = tablaPrestamo.getTabla().convertRowIndexToModel(tablaPrestamo.getTabla().getSelectedRow());
                        campoId.setText(modelo.getValueAt(fila, 2).toString());
                    }
                });

                btnConfirmar.addActionListener(e -> {
                    String idStr = campoId.getText().trim();
                    if (idStr.isEmpty()) {
                        javax.swing.JOptionPane.showMessageDialog(null, "Ingresá el ID del préstamo.", "Campo vacío", javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    int idPrestamo;
                    try {
                        idPrestamo = Integer.parseInt(idStr);
                    } catch (NumberFormatException ex) {
                        javax.swing.JOptionPane.showMessageDialog(null, "El ID debe ser un número.", "ID inválido", javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    Clases.Model.Prestamo prestamo = Repositorios.RepositorioPrestamos.prestamos.get(idPrestamo);
                    if (prestamo == null) {
                        javax.swing.JOptionPane.showMessageDialog(null, "No existe préstamo con ID: " + idPrestamo, "No encontrado", javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    int confirm = javax.swing.JOptionPane.showConfirmDialog(null,
                        "¿Borrar el préstamo ID " + idPrestamo + " del alumno: " + prestamo.getAlumno() + "?",
                        "Confirmar borrado", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);
                    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                        Controller.ControladorView.liberarLibros(prestamo.getLibros());
                        Repositorios.RepositorioPrestamos.prestamos.remove(idPrestamo);
                        javax.swing.JOptionPane.showMessageDialog(null, "Préstamo borrado correctamente.");
                        modelo.setRowCount(0);
                        for (Clases.Model.Prestamo p : Controller.ControladorView.obtenerPrestamos()) {
                            String librosUnidos = String.join(", ", p.getLibros());
                            modelo.addRow(new Object[]{
                                p.getAlumno(), librosUnidos, p.getId(),
                                p.getFechaDePrestamo(), p.getFechaDevolucion(),
                                p.getFechaDevuelta() != null ? p.getFechaDevuelta() : "Pendiente",
                                p.verificarVencimiento()
                            });
                        }
                        campoId.setText("");
                    }
                });

                javax.swing.JPanel panelInferior = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 8));
                panelInferior.add(labelId);
                panelInferior.add(campoId);
                panelInferior.add(btnConfirmar);

                javax.swing.JPanel panelBorrar = new javax.swing.JPanel(new java.awt.BorderLayout());
                panelBorrar.add(tablaPrestamo, java.awt.BorderLayout.CENTER);
                panelBorrar.add(panelInferior, java.awt.BorderLayout.SOUTH);

                ventanaPrincipal.mostrarEnCentro(panelBorrar);
            }
    }

        
    }//GEN-LAST:event_botonBorraraccionListar

    private void accionListar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionListar
        botonEditar.setVisible(false);
        botonCrear.setVisible(false);
        botonListar.setVisible(false);

        switch (menuActual) {

            case "Alumnos" -> {
                TablaAlumno tablaAlumno = new TablaAlumno();
                javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) tablaAlumno.getTabla().getModel();
                modelo.setRowCount(0);
                for (Clases.Model.Alumno a : Controller.ControladorView.obtenerAlumnos()) {
                    modelo.addRow(new Object[]{
                        a.getNombreCompleto(),
                        a.getNroDeDocumento(),
                        a.getEmail(),
                        a.getTelefono(),
                        a.getFechaDeNacimiento(),
                        a.getFacultadPerteneciente()
                    });
                }
                java.util.Comparator<Object> comparatorNombre = (a1, b)
                -> a1.toString().compareToIgnoreCase(b.toString());

                java.util.Comparator<Object> comparatorEdad = (a1, b)
                -> a1.toString().compareTo(b.toString());

                javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter
                = new javax.swing.table.TableRowSorter<>(modelo);

                sorter.setComparator(0, comparatorNombre);
                sorter.setComparator(4, comparatorEdad);

                tablaAlumno.getTabla().setRowSorter(sorter);
                ventanaPrincipal.mostrarEnCentro(tablaAlumno);
            }

            case "Libros" -> {
                TablaLibro tablaLibro = new TablaLibro();
                javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) tablaLibro.getTabla().getModel();
                modelo.setRowCount(0);
                for (Clases.Model.Libro l : Controller.ControladorView.obtenerLibros()) {
                    modelo.addRow(new Object[]{
                        l.getId(),
                        l.getTitulo(),
                        l.getEditorial(),
                        l.getAnhoDePublicacion(),
                        l.getAutor()
                    });
                }
                ventanaPrincipal.mostrarEnCentro(tablaLibro);
            }

            case "Prestamos" -> {
                TablaPrestamo tablaPrestamo = new TablaPrestamo();
                javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) tablaPrestamo.getTabla().getModel();
                modelo.setRowCount(0);
                for (Clases.Model.Prestamo p : Controller.ControladorView.obtenerPrestamos()) {
                    String librosUnidos = String.join(", ", p.getLibros());
                    modelo.addRow(new Object[]{
                        p.getAlumno(),
                        librosUnidos,
                        p.getId(),
                        p.getFechaDePrestamo(),
                        p.getFechaDevolucion(),
                        p.getFechaDevuelta() != null ? p.getFechaDevuelta() : "Pendiente",
                        p.verificarVencimiento()
                    });
                }

                javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter
                = new javax.swing.table.TableRowSorter<>(modelo);
                tablaPrestamo.getTabla().setRowSorter(sorter);

                javax.swing.JTextField campoBusqueda = new javax.swing.JTextField();
                javax.swing.JLabel labelFiltro = new javax.swing.JLabel("Filtrar por alumno: ");

                campoBusqueda.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
                    private void filtrar() {
                        String texto = campoBusqueda.getText().trim();
                        if (texto.isEmpty()) {
                            sorter.setRowFilter(null);
                        } else {
                            sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto, 0));
                        }
                    }

                    public void insertUpdate(javax.swing.event.DocumentEvent e) {
                        filtrar();
                    }

                    public void removeUpdate(javax.swing.event.DocumentEvent e) {
                        filtrar();
                    }

                    public void changedUpdate(javax.swing.event.DocumentEvent e) {
                        filtrar();
                    }
                });

                sorter.setComparator(3, java.util.Comparator.comparing(Object::toString));
                sorter.setComparator(4, java.util.Comparator.comparing(Object::toString));

                javax.swing.JButton botonFechaPrestamo   = new javax.swing.JButton("Ordenar por F. Préstamo");
                javax.swing.JButton botonFechaDevolucion = new javax.swing.JButton("Ordenar por F. Devolución");
                botonFechaPrestamo.addActionListener(e -> sorter.setSortKeys(
                    java.util.List.of(new javax.swing.RowSorter.SortKey(3, javax.swing.SortOrder.ASCENDING))));
            botonFechaDevolucion.addActionListener(e -> sorter.setSortKeys(
                java.util.List.of(new javax.swing.RowSorter.SortKey(4, javax.swing.SortOrder.ASCENDING))));

        javax.swing.JPanel panelBotones = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
        panelBotones.add(botonFechaPrestamo);
        panelBotones.add(botonFechaDevolucion);

        javax.swing.JPanel barraFiltro = new javax.swing.JPanel(new java.awt.BorderLayout(5, 0));
        barraFiltro.add(labelFiltro, java.awt.BorderLayout.WEST);
        barraFiltro.add(campoBusqueda, java.awt.BorderLayout.CENTER);
        barraFiltro.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        javax.swing.JPanel panelSuperior = new javax.swing.JPanel(new java.awt.BorderLayout());
        panelSuperior.add(barraFiltro, java.awt.BorderLayout.NORTH);
        panelSuperior.add(panelBotones, java.awt.BorderLayout.SOUTH);

        javax.swing.JPanel panelFiltro = new javax.swing.JPanel(new java.awt.BorderLayout());
        panelFiltro.add(panelSuperior, java.awt.BorderLayout.NORTH);
        panelFiltro.add(tablaPrestamo, java.awt.BorderLayout.CENTER);
        ventanaPrincipal.mostrarEnCentro(panelFiltro);
        }
        }
    }//GEN-LAST:event_accionListar
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menus;
    private View.BotonAmarilloAlPasar botonAtras;
    private View.BotonAmarilloAlPasar botonBorrar;
    private View.BotonAmarilloAlPasar botonCrear;
    private View.BotonAmarilloAlPasar botonEditar;
    private View.BotonAmarilloAlPasar botonListar;
    // End of variables declaration//GEN-END:variables
}
