/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ThinkPad
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VENTANA
     */
    
    
    
    
    
    public VentanaPrincipal() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        Contenedor = new javax.swing.JPanel();
        panelArriba = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelIzquierda = new javax.swing.JPanel();
        Menus = new javax.swing.JPanel();
        botonAmarilloAlPasar5 = new View.BotonAmarilloAlPasar();
        botonAmarilloAlPasar6 = new View.BotonAmarilloAlPasar();
        botonAmarilloAlPasar7 = new View.BotonAmarilloAlPasar();
        botonAmarilloAlPasar8 = new View.BotonAmarilloAlPasar();
        Centro = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Contenedor.setBackground(new java.awt.Color(255, 0, 0));
        Contenedor.setLayout(new java.awt.BorderLayout());

        panelArriba.setBackground(new java.awt.Color(255, 255, 153));
        panelArriba.setPreferredSize(new java.awt.Dimension(552, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Adobe Express - file.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(204, 102, 0)));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/criuni-91e899b7b3ba52c25a216d214734fcbd20c8538834e691a6a70ff61d65f25f71 (1).png"))); // NOI18N

        javax.swing.GroupLayout panelArribaLayout = new javax.swing.GroupLayout(panelArriba);
        panelArriba.setLayout(panelArribaLayout);
        panelArribaLayout.setHorizontalGroup(
            panelArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArribaLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );
        panelArribaLayout.setVerticalGroup(
            panelArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArribaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        Contenedor.add(panelArriba, java.awt.BorderLayout.PAGE_START);

        panelIzquierda.setBackground(new java.awt.Color(204, 102, 0));
        panelIzquierda.setPreferredSize(new java.awt.Dimension(200, 209));
        panelIzquierda.setLayout(new java.awt.CardLayout());

        Menus.setOpaque(false);

        botonAmarilloAlPasar5.setBackground(new java.awt.Color(204, 102, 0));
        botonAmarilloAlPasar5.setText("Prestamos");
        botonAmarilloAlPasar5.setToolTipText("");
        botonAmarilloAlPasar5.setContentAreaFilled(false);

        botonAmarilloAlPasar6.setBackground(new java.awt.Color(204, 102, 0));
        botonAmarilloAlPasar6.setText("Salir");
        botonAmarilloAlPasar6.setToolTipText("");
        botonAmarilloAlPasar6.setContentAreaFilled(false);
        botonAmarilloAlPasar6.addActionListener(this::botonAmarilloAlPasar6ActionPerformed);

        botonAmarilloAlPasar7.setBackground(new java.awt.Color(204, 102, 0));
        botonAmarilloAlPasar7.setText("Libros");
        botonAmarilloAlPasar7.setContentAreaFilled(false);

        botonAmarilloAlPasar8.setBackground(new java.awt.Color(204, 102, 0));
        botonAmarilloAlPasar8.setText("Alumnos");
        botonAmarilloAlPasar8.setToolTipText("");
        botonAmarilloAlPasar8.setContentAreaFilled(false);

        javax.swing.GroupLayout MenusLayout = new javax.swing.GroupLayout(Menus);
        Menus.setLayout(MenusLayout);
        MenusLayout.setHorizontalGroup(
            MenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenusLayout.createSequentialGroup()
                .addGroup(MenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenusLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(MenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonAmarilloAlPasar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonAmarilloAlPasar6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(MenusLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonAmarilloAlPasar8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAmarilloAlPasar7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        MenusLayout.setVerticalGroup(
            MenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenusLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(botonAmarilloAlPasar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAmarilloAlPasar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAmarilloAlPasar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(botonAmarilloAlPasar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        panelIzquierda.add(Menus, "card2");

        Contenedor.add(panelIzquierda, java.awt.BorderLayout.LINE_START);

        Centro.setBackground(new java.awt.Color(204, 153, 0));

        javax.swing.GroupLayout CentroLayout = new javax.swing.GroupLayout(Centro);
        Centro.setLayout(CentroLayout);
        CentroLayout.setHorizontalGroup(
            CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );
        CentroLayout.setVerticalGroup(
            CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        Contenedor.add(Centro, java.awt.BorderLayout.CENTER);

        getContentPane().add(Contenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAmarilloAlPasar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAmarilloAlPasar6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonAmarilloAlPasar6ActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.out.println("Prueba");
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Centro;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel Menus;
    private View.BotonAmarilloAlPasar botonAmarilloAlPasar5;
    private View.BotonAmarilloAlPasar botonAmarilloAlPasar6;
    private View.BotonAmarilloAlPasar botonAmarilloAlPasar7;
    private View.BotonAmarilloAlPasar botonAmarilloAlPasar8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JPanel panelArriba;
    private javax.swing.JPanel panelIzquierda;
    // End of variables declaration//GEN-END:variables
}
